#allinfo about the action
name: 'make gh-pages branch'
description: 'This action creates a gh-pages branch for a repository and pushes the rocrates to it'
author: 'Decruw Cedric'
branding:
  icon: 'git-branch'
  color: 'blue'

# Inputs:
inputs:
  # The base URI of the RO-Crate
  base_uri:
    description: 'The base URI of the RO-Crate'
    required: true
    default: 'https://example.org/fill_in_your_base_uri/'

runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - ${{ inputs.base_uri }}