prefix schema: <http://schema.org/>

select ?candidate where {
    {?rocrate schema:conformsTo ?candidate .
    [] schema:about ?rocrate .}
    UNION
    {[] schema:hasPart/schema:itemListElement ?candidate .}
    UNION
    {[] schema:hasPart ?candidate .}
}