# this yml file will check if there are python files were updated and if so then run flakes8 on them and fail the build if there are errors if there are then the build will fail and the developer will have to fix the errors before the build will pass
name: Python Lint

on :
    push:
        branches: [ master, main ]
    pull_request:
        branches: [ master, main ]

jobs:

    lint:
        name: Python Lint
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v2
            - name: Set up Python 3.8
              uses: actions/setup-python@v2
              with:
                  python-version: 3.8
            - name: Install dependencies
              run: |
                  python -m pip install --upgrade pip
                  pip install flake8
            - name: Lint with flake8
              run: |
                  flake8 ./src --count --ignore=E501,E203,W503 --max-line-length=79 --statistics
                  if [ $? -eq 1 ]; then exit 1; fi
                

